name: Convert and Release LXGW WenKai Fonts to WOFF2

on:
  # 手动触发
  workflow_dispatch:

jobs:
  convert-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential git wget libbrotli-dev
    
    - name: Get latest release info from LXGW WenKai
      id: lxgw_release
      run: |
        API_URL="https://api.github.com/repos/lxgw/LxgwWenKai/releases/latest"
        # 获取最新的版本信息
        RELEASE_INFO=$(curl -s $API_URL)
        VERSION=$(echo $RELEASE_INFO | grep -o '"tag_name": *"[^"]*"' | cut -d'"' -f4)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Latest version: $VERSION"
    
    - name: Create fonts directory
      run: mkdir -p fonts/ttf fonts/woff2
      
    - name: Download TTF files
      run: |
        # 定义要下载的字体文件
        FONT_FILES=(
          "LXGWWenKai-Light.ttf"
          "LXGWWenKai-Regular.ttf"
          "LXGWWenKai-Medium.ttf"
          "LXGWWenKaiMono-Light.ttf"
          "LXGWWenKaiMono-Regular.ttf"
          "LXGWWenKaiMono-Medium.ttf"
        )
        
        # 构建下载基础URL
        BASE_URL="https://github.com/lxgw/LxgwWenKai/releases/download/${{ env.VERSION }}"
        
        # 逐个下载字体文件
        for FONT_FILE in "${FONT_FILES[@]}"; do
          echo "Downloading $FONT_FILE"
          DOWNLOAD_URL="$BASE_URL/$FONT_FILE"
          echo "URL: $DOWNLOAD_URL"
          wget -q --show-progress -O "fonts/ttf/$FONT_FILE" "$DOWNLOAD_URL" || echo "Warning: Failed to download $FONT_FILE"
          
          # 检查文件是否成功下载
          if [ -f "fonts/ttf/$FONT_FILE" ] && [ -s "fonts/ttf/$FONT_FILE" ]; then
            echo "Successfully downloaded $FONT_FILE"
          else
            echo "Error: $FONT_FILE download failed or file is empty"
            rm -f "fonts/ttf/$FONT_FILE" 2>/dev/null
          fi
        done
        
        # 列出已下载的文件
        echo "Downloaded TTF files:"
        ls -la fonts/ttf/
    
    - name: Install woff2 tool
      run: |
        git clone --recursive https://github.com/google/woff2.git
        cd woff2
        make
        cd ../
    
    - name: Convert TTF to WOFF2
      run: |
        cd fonts/ttf
        for file in *.ttf; do
          if [ -f "$file" ] && [ -s "$file" ]; then
            echo "Converting $file to WOFF2"
            ../../woff2/woff2_compress "$file"
            if [ -f "${file%.ttf}.woff2" ]; then
              mv "${file%.ttf}.woff2" "../woff2/"
              echo "Successfully converted $file to WOFF2"
            else
              echo "Error: Failed to convert $file to WOFF2"
            fi
          fi
        done
        cd ../..
    
    - name: List converted files
      run: |
        echo "WOFF2 files generated:"
        ls -la fonts/woff2/
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: lxgw-woff2-${{ env.VERSION }}
        name: LXGW WenKai WOFF2 Fonts ${{ env.VERSION }}
        body: |
          WOFF2 version of LXGW WenKai fonts, converted from version ${{ env.VERSION }}
          
          Original fonts: https://github.com/lxgw/LxgwWenKai/releases/tag/${{ env.VERSION }}
        files: fonts/woff2/*.woff2
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
